"""Add timeout column to ecs_challenge

Revision ID: 113uj5m91yf2
Revises: 8fb71d82c1e7
Create Date: 2025-11-02 20:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "113uj5m91yf2"
down_revision = "8fb71d82c1e7"
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ecs_challenge", sa.Column("timeout", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ecs_challenge", "timeout")
    # ### end Alembic commands ###

