"""Add timeout column to ecs_challenge

Revision ID: 113uj5m91yf2
Revises: 8fb71d82c1e7
Create Date: 2025-11-02 20:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "113uj5m91yf2"
down_revision = "8fb71d82c1e7"
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    bind = op.get_bind()
    result = bind.execute(text("""
        SELECT COUNT(*) as count
        FROM information_schema.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'ecs_challenge' 
          AND COLUMN_NAME = 'timeout'
    """))
    count = result.fetchone()[0]
    
    if count == 0:
        op.add_column("ecs_challenge", sa.Column("timeout", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping it
    bind = op.get_bind()
    result = bind.execute(text("""
        SELECT COUNT(*) as count
        FROM information_schema.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'ecs_challenge' 
          AND COLUMN_NAME = 'timeout'
    """))
    count = result.fetchone()[0]
    
    if count > 0:
        op.drop_column("ecs_challenge", "timeout")
    # ### end Alembic commands ###

